# Generated by Django 4.2.7 on 2023-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLOSED", "CLOSED"),
                            ("NEARLY_EMPTY", "NEARLY_EMPTY"),
                            ("FEW_PEOPLE", "FEW_PEOPLE"),
                            ("HALF_FULL", "HALF_FULL"),
                            ("CROWED", "CROWED"),
                            ("TOTALLY_FULL", "TOTALLY_FULL"),
                        ],
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("open", models.BooleanField(default=True)),
                ("lower_bound", models.IntegerField(default=0)),
                ("upper_bound", models.IntegerField(default=100)),
            ],
        ),
    ]
