# Generated by Django 4.2.6 on 2023-10-30 10:53

from django.db import migrations

from answers.enums import Reason


def create_some_answers(apps, schema_editor):
    # We make reference to the model here
    Answer = apps.get_model("answers", "Answer")  # noqa: N806

    Answer.objects.create(
        reason_name=Reason.CLOSED.value,
        reason_description="It's closed bro 😞",
        open=False,
    )
    Answer.objects.create(
        reason_name=Reason.CLOSED.value,
        reason_description="What don't you understand in “It's closed” man?",
        open=False,
    )
    Answer.objects.create(
        reason_name=Reason.CLOSED.value,
        reason_description="Maybe later, it's closed for now",
        open=False,
    )

    Answer.objects.create(
        reason_name=Reason.NEARLY_EMPTY.value,
        reason_description="Go for it!",
        upper_bound=20,
    )
    Answer.objects.create(
        reason_name=Reason.NEARLY_EMPTY.value,
        reason_description="Go, go, go!",
        upper_bound=20,
    )
    Answer.objects.create(
        reason_name=Reason.NEARLY_EMPTY.value,
        reason_description="Let's go my friend!",
        upper_bound=20,
    )

    Answer.objects.create(
        reason_name=Reason.FEW_PEOPLE.value,
        reason_description="There's still a lot of places to show your skills 😉",
        lower_bound=20,
        upper_bound=40,
    )
    Answer.objects.create(
        reason_name=Reason.FEW_PEOPLE.value,
        reason_description="It's time to go",
        lower_bound=20,
        upper_bound=40,
    )

    Answer.objects.create(
        reason_name=Reason.HALF_FULL.value,
        reason_description="We live in a free country",
        lower_bound=40,
        upper_bound=60,
    )
    Answer.objects.create(
        reason_name=Reason.HALF_FULL.value,
        reason_description="Your choice",
        lower_bound=40,
        upper_bound=60,
    )
    Answer.objects.create(
        reason_name=Reason.HALF_FULL.value,
        reason_description="It's not empty, but get some fresh air!",
        lower_bound=40,
        upper_bound=60,
    )

    Answer.objects.create(
        reason_name=Reason.CROWED.value,
        reason_description="You really like people, don't you?",
        lower_bound=60,
        upper_bound=80,
    )
    Answer.objects.create(
        reason_name=Reason.CROWED.value,
        reason_description="I'd rather not 😤",
        lower_bound=60,
        upper_bound=80,
    )

    Answer.objects.create(
        reason_name=Reason.TOTALLY_FULL.value,
        reason_description="Someone wants to die here?",
        lower_bound=80,
    )
    Answer.objects.create(
        reason_name=Reason.TOTALLY_FULL.value,
        reason_description="Nope",
        lower_bound=80,
    )
    Answer.objects.create(
        reason_name=Reason.TOTALLY_FULL.value,
        reason_description="No, not now!",
        lower_bound=80,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_some_answers),
    ]
