# Generated by Django 4.2.7 on 2023-11-22 15:01

from django.db import migrations

from answers.enums import Reason


def create_some_answers(apps, schema_editor):
    def create_answer(
        status, description, apps, open=True, lower_bound=0, upper_bound=100
    ):
        # We make reference to the model here
        Answer = apps.get_model("answers", "Answer")  # noqa: N806
        Answer.objects.create(
            status=status,
            description=description,
            open=open,
            lower_bound=lower_bound,
            upper_bound=upper_bound,
        )

    def create_closed_answer(description, apps=apps):
        return create_answer(Reason.CLOSED.name, description, apps, open=False)

    def create_nearly_empty_answer(description, apps=apps):
        return create_answer(
            Reason.NEARLY_EMPTY.name, description, apps, upper_bound=20
        )

    def create_few_people_answer(description, apps=apps):
        return create_answer(
            Reason.FEW_PEOPLE.name, description, apps, lower_bound=20, upper_bound=40
        )

    def create_half_full_answer(description, apps=apps):
        return create_answer(
            Reason.HALF_FULL.name, description, apps, lower_bound=40, upper_bound=60
        )

    def create_crowed_answer(description, apps=apps):
        return create_answer(
            Reason.CROWED.name, description, apps, lower_bound=60, upper_bound=80
        )

    def create_totally_full_answer(description, apps=apps):
        return create_answer(
            Reason.TOTALLY_FULL.name, description, apps, lower_bound=80
        )

    create_closed_answer("It's closed bro 😞")
    create_closed_answer("What don't you understand in “It's closed” man?")
    create_closed_answer("Maybe later, it's closed for now")

    create_nearly_empty_answer("Go for it!")
    create_nearly_empty_answer("Go, go, go!")
    create_nearly_empty_answer("Let's go my friend!")

    create_few_people_answer("There's still a lot of places to show your skills 😉")
    create_few_people_answer("It's time to go")

    create_half_full_answer("We live in a free country")
    create_half_full_answer("Your choice")
    create_half_full_answer("It's not empty, but get some fresh air!")

    create_crowed_answer("You really like people, don't you?")
    create_crowed_answer("I'd rather not 😤")

    create_totally_full_answer("Someone wants to die here?")
    create_totally_full_answer("Nope")
    create_totally_full_answer("No, not now!")


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_some_answers),
    ]
