# Generated by Django 4.2.7 on 2023-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pool",
            fields=[
                ("_id", models.IntegerField(primary_key=True, serialize=False)),
                ("swimming_pool", models.CharField(max_length=255)),
                ("basin", models.CharField(max_length=255)),
                ("is_opened", models.BooleanField(default=False)),
                (
                    "current_capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("maximum_capacity", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField()),
            ],
        ),
    ]
