# Generated by Django 4.2.6 on 2023-10-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('pool_name', models.CharField(max_length=255)),
                ('swimming_pool_name', models.CharField(max_length=255)),
                ('is_opened', models.BooleanField(default=False)),
                ('current_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maximum_capacity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
