# Generated by Django 4.2.6 on 2023-10-31 16:47

from django.db import migrations

from datetime import datetime, timezone

import requests


ONE_DAY = 1


def init_database(apps, schema_editor):
    Pool = apps.get_model("pools", "Pool")

    response = requests.get(
        "https://opendata.bordeaux-metropole.fr/api/explore/v2.1/catalog/datasets/bor_frequentation_piscine_tr/records"
    )
    response.raise_for_status()

    data = response.json()

    for entry in data["results"]:
        updated_at = datetime.fromisoformat(entry["datemiseajour"])

        Pool.objects.create(
            _id=entry["fmizonnum"],
            pool_name=entry["fmizonlib"],
            swimming_pool_name=entry["etablissement_etalib"],
            is_opened=(
                datetime.now(timezone.utc) - updated_at.replace(tzinfo=timezone.utc)
            ).days
            < ONE_DAY
            and entry["entree"] > 0,
            current_capacity=(entry["fmicourante"] / entry["fmizonmax"]) * 100
            if entry["fmizonmax"] > 0
            else 0,
            maximum_capacity=entry["fmizonmax"],
            updated_at=updated_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("pools", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init_database),
    ]
